FROM debian
LABEL maintainer="spamfree@matthieubessat.fr"

RUN apt-get update
RUN apt-get install -y default-jre
RUN apt-get install -y default-jdk

# ADD ./ /app

RUN apt-get install -y curl nano build-essential
RUN curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
RUN sh nodesource_setup.sh
RUN apt-get install -y nodejs

# Install chromium headless
RUN apt install -y chromium

# Debug tools
RUN apt install -y nano

# WORKDIR /app
# RUN npm i 
# RUN node install-karate.js
